apiVersion: v1
kind: Service
metadata:
  name: fangcang-front-svc
  namespace: topic4-1
  labels:
    app: fangcang-front
spec:
  type: NodePort
  selector:
    app: fangcang-front
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 31080
      protocol: TCP
