apiVersion: v1
kind: Service
metadata:
  name: topic4-1-frontend
  namespace: mdc
  labels:
    app: topic4-1-frontend
spec:
  type: NodePort
  selector:
    app: topic4-1-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30484
      protocol: TCP
