<template>
  <div class="registry-page"><el-card><div slot="header" class="toolbar"><span>运行镜像注册</span><div><el-input v-model="query" size="small" clearable placeholder="名称 / 镜像地址" class="search" @keyup.enter.native="load" /><el-button size="small" @click="load">刷新</el-button><el-button size="small" type="primary" @click="openRegister">注册镜像</el-button></div></div>
                               <el-table v-loading="loading" :data="rows"><el-table-column prop="imageId" label="ID" width="70" /><el-table-column prop="name" label="名称" min-width="140" /><el-table-column prop="imageRef" label="镜像地址" min-width="240" show-overflow-tooltip /><el-table-column prop="resolvedDigest" label="Digest" min-width="180" show-overflow-tooltip /><el-table-column prop="taskType" label="任务类型" width="110" /><el-table-column prop="modelType" label="模型类型" width="110" /><el-table-column prop="status" label="状态" width="100" /><el-table-column prop="enabled" label="启用" width="70"><template slot-scope="s">{{ s.row.enabled ? '是' : '否' }}</template></el-table-column><el-table-column label="操作" width="190"><template slot-scope="s"><el-button type="text" @click="act(verifyRuntimeImage,s.row.imageId)">校验</el-button><el-button v-if="!s.row.enabled" type="text" @click="act(activateRuntimeImage,s.row.imageId)">启用</el-button><el-button v-else type="text" @click="act(disableRuntimeImage,s.row.imageId)">停用</el-button></template></el-table-column></el-table>
                               <el-pagination :current-page="page" :page-size="20" :total="total" layout="total, prev, pager, next" @current-change="changePage" /></el-card>
    <el-dialog title="注册运行镜像" :visible.sync="dialog" width="600px"><el-form label-width="110px"><el-form-item label="名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="镜像地址"><el-input v-model="form.imageRef" placeholder="registry.example.com/team/image:tag" /></el-form-item><el-form-item label="任务类型"><el-input v-model="form.taskType" /></el-form-item><el-form-item label="模型类型"><el-input v-model="form.modelType" /></el-form-item><el-form-item label="启动命令"><el-input v-model="commandText" placeholder="python /app/train.py" /></el-form-item><el-form-item label="参数模板"><el-input v-model="argsText" placeholder="--data {dataPath}" /></el-form-item><el-form-item label="数据路径"><el-input v-model="form.dataPathTemplate" /></el-form-item><el-form-item label="拉取 Secret"><el-input v-model="form.pullSecretRef" placeholder="可选，仅填写 Secret 名称" /></el-form-item></el-form><span slot="footer"><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="submit">注册</el-button></span></el-dialog>
  </div>
</template>
<script>
import { fetchRuntimeImages, registerRuntimeImage, verifyRuntimeImage, activateRuntimeImage, disableRuntimeImage } from '@/api/registrationApi'
export default { name: 'RuntimeImageRegistry', data: () => ({ query: '', page: 1, total: 0, rows: [], loading: false, dialog: false, commandText: 'python /app/train.py', argsText: '', form: {}}), created() { this.load() }, methods: {
  verifyRuntimeImage, activateRuntimeImage, disableRuntimeImage,
  async load() { this.loading = true; try { const r = await fetchRuntimeImages({ page: this.page, pageSize: 20, query: this.query }); this.rows = r.list || []; this.total = r.total || 0 } catch (e) { this.$message.error(e.message || '加载失败') } finally { this.loading = false } },
  openRegister() { this.form = { name: '', imageRef: '', taskType: '', modelType: '', dataPathTemplate: '/data/{dataset}', pullSecretRef: '' }; this.commandText = 'python /app/train.py'; this.argsText = ''; this.dialog = true },
  async submit() { try { const payload = { ...this.form, command: this.commandText.trim().split(/\s+/).filter(Boolean), argsTemplate: this.argsText.trim() ? this.argsText.trim().split(/\s+/) : [] }; await registerRuntimeImage(payload); this.dialog = false; this.$message.success('镜像已注册，请执行校验后启用'); await this.load() } catch (e) { this.$message.error(e.message || '注册失败') } },
  async act(api, id) { try { await api(id); this.$message.success('操作完成'); await this.load() } catch (e) { this.$message.error(e.message || '操作失败') } }, changePage(page) { this.page = page; this.load() }
}}
</script>
<style scoped>.registry-page{padding:20px}.toolbar{display:flex;align-items:center;justify-content:space-between;font-weight:600}.search{width:240px;margin-right:8px}.el-pagination{margin-top:18px;text-align:right}</style>
